version: '3.8'

services:
  postgres:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: BladeRunner2049
      POSTGRES_DB: bookstore
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  web-crawler:
    build: .
    environment:
      DB_HOST: postgres
      DB_PORT: 5432
      DB_USER: postgres
      DB_PASSWORD: BladeRunner2049
      DB_NAME: bookstore
    depends_on:
      - postgres

volumes:
  postgres-data:
    driver: local
